feat: abci event indexing
Adds the postgres container, with pvc, and updates the cometbft config
to publish events. Doesn't clean up if indexing is later disabled,
thought.

Includes auto-reloading via external helm chart, for faster dev loops.

diff --git a/tools/penumbra-operator/files/pd-init b/tools/penumbra-operator/files/pd-init
--- a/tools/penumbra-operator/files/pd-init
+++ b/tools/penumbra-operator/files/pd-init
@@ -27,8 +27,28 @@ if ! test -d "$penumbra_network_dir" ; then
     fi
 fi
 
+# Begin customization of CometBFT config
+if [[ "${PENUMBRA_COMETBFT_INDEXER:-}" = "psql" ]] ; then
+    >&2 echo "INFO: Enabling CometBFT event indexing";
+    # The operator will set this env var, so it should always be defined, but let's confirm.
+    if [[ -z "${COMETBFT_POSTGRES_CONNECTION_URL:-}" ]]; then
+        >&2 echo "ERROR: CometBFT event indexing was requested, but COMETBFT_POSTGRES_CONNECTION_URL is undefined";
+        exit 1
+    fi
+
+    # Sure would be nice to have a TOML-aware editing capability here. Oh, well.
+    sed -i -e "/^psql-conn/d ; s#^indexer.*#indexer = \"psql\"\\npsql-conn = \"$COMETBFT_POSTGRES_CONNECTION_URL\"#" \
+        "${penumbra_network_dir}/node0/cometbft/config/config.toml"
+else
+    >&2 echo "INFO: Skipping configuration of  CometBFT event indexing";
+    # Disable indexing, in case spec changed from enable_indexing=false -> true.
+    sed -i -e "/^psql-conn/d ; s#^indexer.*#indexer = \"kv\"#" \
+        "${penumbra_network_dir}/node0/cometbft/config/config.toml"
+fi
+
+
 # set ownership for pd user
-chown -R 1000:1000 /home/penumbra/.penumbra/network_data
+chown -R 1000:1000 "$penumbra_network_dir/node0"
 
 # set ownership for cometbft configs to match cometbft container "tmuser" uid/gid
-chown -R 100:1000 /home/penumbra/.penumbra/network_data/node0/cometbft
+chown -R 100:1000 "${penumbra_network_dir}/node0/cometbft"
