feat: network crd
Adds spec for `PenumbraNetwork`. Also shoves things around so there's a
`crate::crd::` namespace now. Uses owner references to ensure smooth
cleanup. Uses unique script names for each identity.

Adjusts the validators.json to write to a unique ConfigMap,
otherwise concurrent PenumbraNetworks will clobber, and genesis will
fail if num_validators is different.

build: add yq to env

Enabling `publish-not-ready-addresses` on the Service objects for the
validators was critical. Without it, the validators couldn't
communicate, because they need network access to each other in order to
bootstrap and satisfy the readinessprobe.

Failure at the genesis stage could still lead to validators starting,
which is bad, but genesis failure is worse, so full cleanup makes sense.
Maybe with actual integration testing it'll be clearer how to handle
those.

diff --git a/tools/penumbra-operator/files/pd-init b/tools/penumbra-operator/files/pd-init
--- a/tools/penumbra-operator/files/pd-init
+++ b/tools/penumbra-operator/files/pd-init
@@ -3,47 +3,61 @@
 set -euo pipefail
 
 
+
 # we must write into a subdir of the volumeMount, because the "--network-dir" arg
 # to "pd network join" must point to a non-existent directory, and the volumeMount
 # will always exist.
 penumbra_network_dir="/home/penumbra/.penumbra/network_data"
 
-if ! test -d "$penumbra_network_dir" ; then
-    echo "No pre-existing network data, pulling fresh info"
-    # shellcheck disable=SC2086
-    pd network --network-dir "$penumbra_network_dir" join \
-        --tendermint-p2p-bind 0.0.0.0:26656 \
-        --tendermint-rpc-bind 0.0.0.0:26657 \
-        "$PENUMBRA_BOOTSTRAP_URL"
+# Only munge state if there's a bootstrap url set.
+if [[ -n "${PENUMBRA_BOOTSTRAP_URL:-}" ]] ; then
+    if ! test -d "$penumbra_network_dir" ; then
+        >&2 echo "No pre-existing network data, pulling fresh info"
+        # shellcheck disable=SC2086
+        pd network --network-dir "$penumbra_network_dir" join \
+            --tendermint-p2p-bind 0.0.0.0:26656 \
+            --tendermint-rpc-bind 0.0.0.0:26657 \
+            "$PENUMBRA_BOOTSTRAP_URL"
 
-    if [[ -n "${PENUMBRA_CUSTOM_ARCHIVE_URL:-}" ]] ; then
-        dest_archive="${penumbra_network_dir}/$(basename "$PENUMBRA_CUSTOM_ARCHIVE_URL")"
-        >&2 echo "Downloading archive from $PENUMBRA_CUSTOM_ARCHIVE_URL ..."
-        while true; do sleep 300; ls -sh "$dest_archive"; done &
-        curl -# -sSfL -o "$dest_archive" "$PENUMBRA_CUSTOM_ARCHIVE_URL"
-        >&2 echo "Extracting archive..."
-        tar -xzf "$dest_archive" -C "${penumbra_network_dir}/node0/"
-        >&2 echo "Done, archive extracted"
+        if [[ -n "${PENUMBRA_CUSTOM_ARCHIVE_URL:-}" ]] ; then
+            dest_archive="${penumbra_network_dir}/$(basename "$PENUMBRA_CUSTOM_ARCHIVE_URL")"
+            >&2 echo "Downloading archive from $PENUMBRA_CUSTOM_ARCHIVE_URL ..."
+            while true; do sleep 300; ls -sh "$dest_archive"; done &
+            curl -# -sSfL -o "$dest_archive" "$PENUMBRA_CUSTOM_ARCHIVE_URL"
+            >&2 echo "Extracting archive..."
+            tar -xzf "$dest_archive" -C "${penumbra_network_dir}/node0/"
+            >&2 echo "Done, archive extracted"
+        fi
+
+        # Begin customization of CometBFT config
+        if [[ "${PENUMBRA_COMETBFT_INDEXER:-}" = "psql" ]] ; then
+            >&2 echo "INFO: Enabling CometBFT event indexing";
+            # The operator will set this env var, so it should always be defined, but let's confirm.
+            if [[ -z "${COMETBFT_POSTGRES_CONNECTION_URL:-}" ]]; then
+                >&2 echo "ERROR: CometBFT event indexing was requested, but COMETBFT_POSTGRES_CONNECTION_URL is undefined";
+                exit 1
+            fi
+
+            # Sure would be nice to have a TOML-aware editing capability here. Oh, well.
+            sed -i -e "/^psql-conn/d ; s#^indexer.*#indexer = \"psql\"\\npsql-conn = \"$COMETBFT_POSTGRES_CONNECTION_URL\"#" \
+                "${penumbra_network_dir}/node0/cometbft/config/config.toml"
+        else
+            >&2 echo "INFO: Skipping configuration of  CometBFT event indexing";
+            # Disable indexing, in case spec changed from enable_indexing=false -> true.
+            sed -i -e "/^psql-conn/d ; s#^indexer.*#indexer = \"kv\"#" \
+                "${penumbra_network_dir}/node0/cometbft/config/config.toml"
+        fi
     fi
-fi
 
-# Begin customization of CometBFT config
-if [[ "${PENUMBRA_COMETBFT_INDEXER:-}" = "psql" ]] ; then
-    >&2 echo "INFO: Enabling CometBFT event indexing";
-    # The operator will set this env var, so it should always be defined, but let's confirm.
-    if [[ -z "${COMETBFT_POSTGRES_CONNECTION_URL:-}" ]]; then
-        >&2 echo "ERROR: CometBFT event indexing was requested, but COMETBFT_POSTGRES_CONNECTION_URL is undefined";
-        exit 1
-    fi
-
-    # Sure would be nice to have a TOML-aware editing capability here. Oh, well.
-    sed -i -e "/^psql-conn/d ; s#^indexer.*#indexer = \"psql\"\\npsql-conn = \"$COMETBFT_POSTGRES_CONNECTION_URL\"#" \
-        "${penumbra_network_dir}/node0/cometbft/config/config.toml"
 else
-    >&2 echo "INFO: Skipping configuration of  CometBFT event indexing";
-    # Disable indexing, in case spec changed from enable_indexing=false -> true.
-    sed -i -e "/^psql-conn/d ; s#^indexer.*#indexer = \"kv\"#" \
-        "${penumbra_network_dir}/node0/cometbft/config/config.toml"
+    >&2 echo "No bootstrap URL set, not touching local state"
+    set +e
+    find "$penumbra_network_dir"
+    ls -lR "$penumbra_network_dir"
+    find /home/penumbra
+    ls -lR /home/penumbra
+    grep -i seed /home/penumbra/.penumbra/network_data/node0/cometbft/config/config.toml
+    exit 0
 fi
 
 
