feat: actually support event indexing
Hooked up a few needed hoses. Now, the pg container and db is created,
with the schema initialized, but the cometbft config isn't updated on
the fly.

TODO: add an env var for the init container that includes the hash of
the script.

Tried to set enable_indexing=true by default, but doesn't look like it's
taking effect.

diff --git a/tools/penumbra-operator/files/pd-init b/tools/penumbra-operator/files/pd-init
--- a/tools/penumbra-operator/files/pd-init
+++ b/tools/penumbra-operator/files/pd-init
@@ -11,6 +11,7 @@ penumbra_network_dir="/home/penumbra/.penumbra/network_data"
 
 # Only munge state if there's a bootstrap url set.
 if [[ -n "${PENUMBRA_BOOTSTRAP_URL:-}" ]] ; then
+
     if ! test -d "$penumbra_network_dir" ; then
         >&2 echo "No pre-existing network data, pulling fresh info"
         # shellcheck disable=SC2086
@@ -27,32 +28,34 @@ if [[ -n "${PENUMBRA_BOOTSTRAP_URL:-}" ]] ; then
             >&2 echo "Extracting archive..."
             tar -xzf "$dest_archive" -C "${penumbra_network_dir}/node0/"
             >&2 echo "Done, archive extracted"
+            # Clean up archive because it's probably ~100GB
+            rm -vf "$dest_archive"
+        fi
+    fi
+
+    # Begin customization of CometBFT config
+    if [[ "${PENUMBRA_COMETBFT_INDEXER:-}" = "psql" ]] ; then
+        >&2 echo "INFO: Enabling CometBFT event indexing";
+        # The operator will set this env var, so it should always be defined, but let's confirm.
+        if [[ -z "${COMETBFT_POSTGRES_CONNECTION_URL:-}" ]]; then
+            >&2 echo "ERROR: CometBFT event indexing was requested, but COMETBFT_POSTGRES_CONNECTION_URL is undefined";
+            exit 1
         fi
 
-        # Begin customization of CometBFT config
-        if [[ "${PENUMBRA_COMETBFT_INDEXER:-}" = "psql" ]] ; then
-            >&2 echo "INFO: Enabling CometBFT event indexing";
-            # The operator will set this env var, so it should always be defined, but let's confirm.
-            if [[ -z "${COMETBFT_POSTGRES_CONNECTION_URL:-}" ]]; then
-                >&2 echo "ERROR: CometBFT event indexing was requested, but COMETBFT_POSTGRES_CONNECTION_URL is undefined";
-                exit 1
-            fi
+        # Sure would be nice to have a TOML-aware editing capability here. Oh, well.
+        sed -i -e "/^psql-conn/d ; s#^indexer.*#indexer = \"psql\"\\npsql-conn = \"$COMETBFT_POSTGRES_CONNECTION_URL\"#" \
+            "${penumbra_network_dir}/node0/cometbft/config/config.toml"
+    else
+        >&2 echo "INFO: Skipping configuration of  CometBFT event indexing";
+        # Disable indexing, in case spec changed from enable_indexing=false -> true.
+        sed -i -e "/^psql-conn/d ; s#^indexer.*#indexer = \"kv\"#" \
+            "${penumbra_network_dir}/node0/cometbft/config/config.toml"
+    fi
 
-            # Sure would be nice to have a TOML-aware editing capability here. Oh, well.
-            sed -i -e "/^psql-conn/d ; s#^indexer.*#indexer = \"psql\"\\npsql-conn = \"$COMETBFT_POSTGRES_CONNECTION_URL\"#" \
-                "${penumbra_network_dir}/node0/cometbft/config/config.toml"
-        else
-            >&2 echo "INFO: Skipping configuration of  CometBFT event indexing";
-            # Disable indexing, in case spec changed from enable_indexing=false -> true.
-            sed -i -e "/^psql-conn/d ; s#^indexer.*#indexer = \"kv\"#" \
-                "${penumbra_network_dir}/node0/cometbft/config/config.toml"
-        fi
-
-        if [[ -n "${PENUMBRA_COMETBFT_SEEDS:-}" ]] ; then
-            >&2 echo "INFO: Setting CometBFT peers '${PENUMBRA_COMETBFT_SEEDS}'"
-            sed -i -e "s#^seeds.*#seeds = \"$PENUMBRA_COMETBFT_SEEDS\"#" \
-                "${penumbra_network_dir}/node0/cometbft/config/config.toml"
-        fi
+    if [[ -n "${PENUMBRA_COMETBFT_SEEDS:-}" ]] ; then
+        >&2 echo "INFO: Setting CometBFT peers '${PENUMBRA_COMETBFT_SEEDS}'"
+        sed -i -e "s#^seeds.*#seeds = \"$PENUMBRA_COMETBFT_SEEDS\"#" \
+            "${penumbra_network_dir}/node0/cometbft/config/config.toml"
     fi
 
 else
